<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '69d698a7eb1794785bf70246cb0fec80',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/boutique?serverVersion=15&charset=utf8',
  'MAILER_URL' => 'null://localhost',
);
