#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
    path: /logout
    methods: GET
    
app_admin:
    path:          /admin
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template:  'static/index.html.twig'

app_quoi:
    path:          /c-est-quoi-essouk-shop
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template:  'static/quoi.html.twig'

app_conditions:
    path:          /conditions-d-utilisation
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render.html
        template:  'static/conditions.html.twig'

app_mailling_moteur:
    path:          /augmenter-vos-ventes
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template:  'static/augmenter-vos-ventes.html.twig'

app_questions:
    path:          /questions-frequentes
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template:  'static/questions-frequentes.html.twig'
