<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXuyVZDw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXuyVZDw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXuyVZDw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXuyVZDw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXuyVZDw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XuyVZDw',
    'container.build_id' => 'eb777393',
    'container.build_time' => 1681180437,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXuyVZDw');
